#!/bin/bash

set -e


# Utilities

no_edit_msg="// DO NOT EDIT THIS FILE DIRECTLY!\n// Generated by the build process\n"

get_filename() {
  bn=$(basename "$1")
  fn=${bn%.*}
  echo $fn
}

prepend_to_file() {
  filepath="$1"
  text="$2"

  echo "$text" | cat - "$filepath" > /tmp/tempfile && mv /tmp/tempfile "$filepath"
}

# Build

build_style_tokens() {
  tokens_dir='src/styles/tokens'
  mkdir -p "$tokens_dir"

  yaml_to_json() {
    src="$1"
    filename=$(get_filename "$src")

    yaml2json "$src" > "$tokens_dir/$filename.json" --pretty
  }

  json_to_scss() {
    src="$1"
    filename=$(get_filename "$src")

    json-to-scss "$src" "$tokens_dir/_$filename.scss" --p="\$$filename: "
    prepend_to_file "$tokens_dir/_$filename.scss" "$no_edit_msg"

    json-to-scss "$src" "$tokens_dir/_$filename-vars.scss" --p="\$$filename-" --fk
    prepend_to_file "$tokens_dir/_$filename-vars.scss" "$no_edit_msg"
  }

  yaml_files=(
    'node_modules/rtg-design/src/tokens/system.yaml'
    'node_modules/rtg-design/src/tokens/theme.yaml'
  )

  for file in ${yaml_files[@]}
  do
    yaml_to_json "$file"
  done

  json_files=(
    "$tokens_dir/system.json"
    "$tokens_dir/theme.json"
  )

  for file in ${json_files[@]}
  do
    json_to_scss "$file"
  done
}

main() {
  build_style_tokens
}

main
